# Generated by Django 2.1.4 on 2019-06-03 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TodoList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(default='', help_text='location', max_length=30, verbose_name='location')),
                ('priority', models.IntegerField(default=0, help_text='priority', verbose_name='priority')),
                ('time', models.DateTimeField(help_text='date time', verbose_name='data tiem')),
                ('repeat', models.IntegerField(default=0, help_text='repeat', verbose_name='repeat')),
                ('notes', models.TextField(default='', help_text='notes', verbose_name='notes')),
                ('alarm', models.IntegerField(default=0, help_text='alarm', verbose_name='alarm')),
                ('reminder', models.IntegerField(default=0, help_text='reminder', verbose_name='reminder')),
                ('name', models.CharField(default='', help_text='name', max_length=30, verbose_name='name')),
            ],
            options={
                'verbose_name': 'todoitme',
                'verbose_name_plural': 'todoitme',
            },
        ),
    ]
