# Generated by Django 2.1.4 on 2019-06-03 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolist',
            name='userid',
            field=models.IntegerField(default=0, help_text='userid', verbose_name='userid'),
        ),
    ]
